[package]
name = "cast-analyzer"
version = "1.0.0"
description = "CAST Database Analyzer"
authors = ["FBI CAST Team"]
license = "US Government"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"