name: Build CAST Database Analyzer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: npm install

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'CAST Database Analyzer v__VERSION__'
          releaseBody: |
            ## CAST Database Analyzer ${{ github.ref_name }}
            
            Professional telecommunications forensics tool for analyzing CDR records, text messages, and digital evidence.
            
            ### Installation:
            1. Download the .msi installer below
            2. Run the installer as administrator
            3. Launch "CAST Database Analyzer" from Start Menu
            
            ### Features:
            - Multi-format file support (CSV, Excel, TXT, HTML, PDF)
            - Advanced phone number extraction
            - Cross-reference analysis
            - Professional forensics UI
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: false