name: Build Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List build artifacts
        run: |
          echo "Build artifacts:"
          dir dist-electron
        shell: cmd

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist-electron/*.exe
            dist-electron/*.msi
          draft: false
          prerelease: false
          name: 'CAST Database Analyzer ${{ github.ref_name }}'
          body: |
            ## CAST Database Analyzer ${{ github.ref_name }}

            **Professional telecommunications forensics tool for Windows**

            ### Downloads:
            - **Setup.exe**: Full installer with automatic updates
            - **Portable.exe**: Portable version (no installation required)

            ### Installation:
            1. Download the Setup.exe file
            2. Run as administrator
            3. Follow the installation wizard
            4. Launch from Start Menu

            ### Features:
            - Multi-format file support (CSV, Excel, TXT, HTML, PDF)
            - Advanced phone number extraction
            - Email and IP address analysis
            - Cross-reference analysis
            - Professional forensics UI
            - Save/Load investigation databases

            ### System Requirements:
            - Windows 10 or later
            - 4GB RAM minimum
            - 100MB free disk space

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}