name: Build Tauri App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js (for build script only)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Rust targets
      run: rustup target add x86_64-pc-windows-msvc

    - name: Prepare frontend
      run: node build-tauri.js

    - name: Build Tauri app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cargo tauri build

    - name: List build artifacts
      run: |
        echo "Build artifacts:"
        dir src-tauri\target\release\bundle
      shell: cmd

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-windows-${{ github.ref_name }}
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe

  release:
    needs: build-tauri
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: tauri-windows-${{ github.ref_name }}
        path: ./release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/**/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}