name: Build Tauri App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "./src-tauri -> target"

    - name: Prepare frontend and icons
      run: |
        node build-tauri.js
        node create-icon.js

    - name: Verify ICO file exists
      run: |
        if (Test-Path "src-tauri/icons/icon.ico") {
          Write-Host "ICO file found: $(Get-Item 'src-tauri/icons/icon.ico' | Select-Object Length)"
        } else {
          Write-Host "ICO file missing - creating fallback"
          Copy-Item "src-tauri/icons/32x32.png" "src-tauri/icons/icon.ico"
        }
      shell: powershell

    - name: Build and Release Tauri App
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: ${{ github.ref_name }}
        releaseName: 'CAST Database Analyzer v${{ github.ref_name }}'
        releaseBody: 'Tauri-based Windows executable with native drag-and-drop support. Package size: ~2.5MB'
        releaseDraft: false
        prerelease: false